---
- name: Add PHP Repository
  apt_repository:
    repo: 'ppa:ondrej/php5-5.6'
    state: present

- name: Install PHP and PHP-FPM
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - php5-fpm
    - php5-cli
    - php5-pgsql
    - php5-mysql
    - php5-sqlite
    - php5-curl
    - php5-gd
    - php5-gmp
    - php5-mcrypt
    - php5-memcached
    - php5-imagick
    - php5-intl
  notify:
    - Start PHP-FPM

- name: Add PHP-FPM PHP Configuration
  template:
    src: php.ini.j2
    dest: /etc/php5/fpm/php.ini
  notify:
    - Restart PHP-FPM

- name: Add Default Resource Pool
  template:
    src: www.conf.j2
    dest: /etc/php5/fpm/pool.d/www.conf
  notify:
    - Restart PHP-FPM
