---
- name: Install MariaDB repository
  apt_repository:
    repo: 'deb http://lon1.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu trusty main'
    state: present

- name: Add repository key to the system
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "0xcbcb082a1bb943db"

- name: Install MySQL
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Start the MySQL service
  service:
    name: mysql
    state: started

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ db_password }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Delete anonymous MySQL server user for $server_hostname
  mysql_user:
    user: ""
    host: localhost
    state: absent

- name: Delete anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state: absent

- name: Remove the MySQL test database
  mysql_db:
    db: test
    state: absent

- name: Create a database
  mysql_db:
    name: "{{ db_name }}"
    state: present
