---
- name: Installing ufw
  apt:
    pkg: ufw
    state: present

- name: Allow ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22    # ssh
    - 25    # mail
    - 80    # http
    - 443   # https
    - 465   # smtp email
    - 3306  # mysql
    - 11211 # memcached

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
